name: policy-ref
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:         # everything under this, installed by conda
- python=3.7
- pip
- pytorch=1.2.0
- torchvision=0.4.0
- cudatoolkit=10.0
- future
- tensorboard
- numpy
- scipy
- scikit-learn
- scikit-image
- h5py
- cython
- tqdm
- natsort
- tabulate
- yacs
- pytest
- matplotlib=3.1.1
- pillow=6.1
- pip:
  - opencv-python==4.2.0.34
  - gym==0.12.0
  - atari-py==0.1.4
  - torch-scatter==1.4.0
  - torch-sparse==0.4.3
  - torch-cluster==1.4.5
  - torch-geometric==1.3.2
  - git+git://github.com/lanpa/tensorboardX.git@022f060f9438c4f5e71880bccb474671f5db4450